### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "asd798852"
}

### 호텔 목록 조회(정상응답)
GET http://localhost:8080/api/v1/hotels?page=0


### 호텔 상세 조회(정상응답)
GET http://localhost:8080/api/v1/hotels/1

### 호텔 상세 조회(존재하지않는호텔)
GET http://localhost:8080/api/v1/hotels/50


### 예약 생성(정상응답)
POST http://localhost:8080/api/v1/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3NzQzMzgzMywiZXhwIjoxNzc3NDM1NjMzfQ.MyDBnIthVL4lf96ZM_j0UU72KKPyN-6NpNEmFCsWjz8

{
  "reservationId": "550e8400-e29b-41d4-a716-446655440000",
  "hotelId": 1,
  "roomTypeId": 1,
  "startDate": "2026-04-29",
  "endDate": "2026-04-30",
  "numberOfRoomsToReserve": 1
}

### 예약 조회(정상응답)
GET http://localhost:8080/api/v1/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3NzQzMzgzMywiZXhwIjoxNzc3NDM1NjMzfQ.MyDBnIthVL4lf96ZM_j0UU72KKPyN-6NpNEmFCsWjz8

### 호텔 생성(정상응답)
POST http://localhost:8080/api/v1/hotels
Content-Type: application/json

{
  "hotelName": "Grand Hotel Seoul",
  "address": "Gangnam-gu, Seoul",
  "latitude": 37.4979,
  "longitude": 127.0276,
  "imageUrl": null,
  "checkInTime": "14:00:00",
  "checkOutTime": "11:00:00"
}

### 호텔 수정(정상응답)
PUT http://localhost:8080/api/v1/hotels/5
Content-Type: application/json

{
  "hotelName": "Grand Seoul",
  "address": "Gangnam-gu, Seoul",
  "latitude": 37.4979,
  "longitude": 127.0276,
  "imageUrl": null,
  "checkInTime": "15:00:00",
  "checkOutTime": "11:00:00"
}

### 호텔 삭제(정상응답)
DELETE http://localhost:8080/api/v1/hotels/5

### 호텔 삭제(없는 호텔)
DELETE http://localhost:8080/api/v1/hotels/500

### 객실타입 생성(정상응답)
POST http://localhost:8080/api/v1/hotels/1/roomtypes
Content-Type: application/json

{
  "roomTypeName": "스위트 룸",
  "maxOccupancy": 2,
  "imageUrl": null
}


### 객실타입 수정(정상응답)
PUT http://localhost:8080/api/v1/hotels/1/roomtypes/1
Content-Type: application/json

{
  "roomTypeName": "스위쯔 룸",
  "maxOccupancy": 5,
  "imageUrl": null
}

### 객실타입 삭제(정상응답)
DELETE http://localhost:8080/api/v1/hotels/2/roomtypes/3

### 객실 생성(정상응답)
POST http://localhost:8080/api/v1/hotels/1/roomtypes/9
Content-Type: application/json

{
  "roomName": "작은방2",
  "floor": "2",
  "number": "201"
}

### 객실 수정(정상응답)

### 객실 삭제(정상응답)