spring:
  application:
    name: hotel-server
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: never
  data:
    redis:
      host: localhost
      port: 6379
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration
mybatis:
  #xml 위치(sql이 저장된)
  mapper-locations: classpath:mapper/*.xml
  #칼럼명의 aliases 위치 설정
  type-aliases-package: com.hotel.hotel_server.domain, com.hotel.hotel_server.dto
  #snake-case(DB) -> camel-case(Java) 자동매핑 설정
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8082
