spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        # reservation-server 라우팅
        - id: reservation-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/reservations/**, /api/v1/hotels/**

        # payment-server 라우팅
        - id: payment-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/payments/**

        # order-server 라우팅
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/orders/**
jwt:
  secret: testSecretKeyForTestingPurposeOnly1234567890
  access-expiration: 1800000
  refresh-expiration: 86400000

server:
  port: 8000